### ISSUE TITLE
You have modifications to your git worktree.

### ISSUE THREAD

**Issue by adrianiskandar** [decaffeinate/bulk-decaffeinate#98] opened 2017-04-11 07:26 UTC
The tool keeps saying:
"You have modifications to your git worktree.
Please revert or commit them before running convert."

But my git work tree is clean. I even delete my .git folder once and the tool still complained.

I think I manually deleted the files created when I run command 'check' and that left the tool in a bad state but is incredibly annoying. Do you know an easy way to fix it? Thanks.

**Comment by alangpierce** [comment] 2017-04-12 18:17
Thanks for reporting! I've run into this as well, but just when running bulk-decaffeinate as part of a script after cloning ~150 repos into the same directory. I *think* the files generated by `check` shouldn't cause this error, but I'm not 100% sure. When I ran into it, `git status` showed no changes, which was especially weird.

My guess is that it's some issue with the nodegit library (maybe a bad cache or something), and the problem will either be fixed or at least be easier to diagnose if we move back to just using the native git installation instead. There's already some progress on that in #86 (sorry for the delay @refack!), hopefully that can get done reasonably soon.

**Comment by alangpierce** [comment] 2017-04-17 02:35
@adrianiskandar I made a change to use a different git library which I think should be more reliable here. The similar issue I ran into seems to be fixed now with the latest bulk-decaffeinate, so I'm going to call this closed. But let me know if you're still running into issues after updating to the latest version.

**Comment by zachberry** [comment] 2017-05-08 20:32
I ran into an issue where I had a config file in my working directory which resulted in an untracked file. That seemed to be causing bulk-decaffeinate to complain with this error. I'd rather not commit this file since I really only need it once. Open to discussion that committing the config is a good idea but regardless this seems to be unexpected behavior, instead I'm thinking the clean worktree check should exclude untracked files.

**Comment by alangpierce** [comment] 2017-05-08 20:56
@zachberry you're right, I think it should be reasonable to change the check to allow untracked files. Probably should be an easy fix. I'd mainly need to make sure there isn't any code path that would add and commit the file unexpectedly (from my reading of the code, there isn't).

FWIW, a workaround without committing the file (or adding it to `.gitignore`) is to add it to `.git/info/exclude`, which is like your personal `.gitignore`.

**Comment by zachberry** [comment] 2017-05-08 21:17
Ah, wasn't aware of `.git/info/exclude`, thanks!

**Comment by zachberry** [comment] 2017-05-08 21:52
Perhaps it should warn in this case actually. I had `convert` fail meaning I had several new untracked `original.coffee` and `js` files which I could clean up with `git clean -f`, but had I not cleaned up my untracked files I wouldn't have been able to run `git clean -f` as easily.

**Closed** 2017-05-13 21:25 UTC

**Comment by alangpierce** [comment] 2017-05-13 21:35
I just released a change that makes it warn instead of fail if you have untracked files. Let me know if you run into any issues.
